services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: hsbc
      POSTGRES_PASSWORD: hsbc123
      POSTGRES_DB: dwh_hsbc
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "3000:3000"
